default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gethn-api_development

test:
  <<: *default
  database: gethn-api_test
production:
  <<: *default
  database: gethn-api_production
  username: gethn-api
  password: <%= ENV['GETHN-API_DATABASE_PASSWORD'] %>
